#!/bin/sh

LaunchAgent=/Library/LaunchAgents/com.gitlab.gitlab-runner.plist

loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }' )
userID=$( id -u $loggedInUser )
/bin/launchctl bootstrap gui/$userID "$LaunchAgent"

exit 0